## 導入numpy語句,別名為 <span style="color: red;"> np</red>

In [43]:
import numpy as np

#### 創建一個變數名為 <span style="color: red;">arr1</span> 的一維數組, 裡面元素為整數 8, 10, -15, 2, -6, 建立後輸出 <span style="color: red;">arr1</span>




In [45]:
arr1 = np.array([8, 10, -15, 2, -6])
arr1

#arr1 8, 10, -15, 2, -6

array([  8,  10, -15,   2,  -6])

#### 創建一個變數名為 <span style="color: red;">arr2</span> 的二維數組, 裡面元素有兩個數組, 由整數 1, 3, 5 組成的一維數組
#### 以及整數 2, 4, 6 組成的一維數組, 建立後輸出 <span style="color: red;">arr2</span>



In [46]:
arr2 = np.array([[1, 3, 5], [2, 4, 6]])
arr2
# arr2 1, 3, 5 
# 2, 4, 6


array([[1, 3, 5],
       [2, 4, 6]])

#### 輸出 <span style="color: red;">arr1</span> 和 <span style="color: red;">arr2</span> 的維度、形狀、元素數量和元素類型。


In [59]:
# arr1 ,arr2
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)






1
2
(5,)
(2, 3)
5
6
int64
int64


#### 建立一個變數名 <span style="color: red;">arr_zero</span> 的一維數組, 裡面有 5 個 0,最後輸出


In [74]:
# arr_zero
arr_zero = np.zeros(5)
arr_zero


array([0., 0., 0., 0., 0.])

#### 建立一個變數名 <span style="color: red;">arr_ones</span> 的一維數組, 裡面有 5 個 1


In [75]:
# arr_ones
arr_ones = np.ones(5)
arr_ones


array([1., 1., 1., 1., 1.])

#### 建立一個變數名 <span style="color: red;">arr_even</span> 的一維數組, 裡面的元素為 4（包括 4）到 16（包括 16 ）之間的偶數。


In [76]:
# arr_even
arr_even = np.arange(4, 17, 2)
arr_even



array([ 4,  6,  8, 10, 12, 14, 16])